# Generated by Django 5.2.7 on 2025-10-27 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(default='пер.', max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('other_titles', models.CharField(blank=True, max_length=256)),
                ('connect', models.TextField(blank=True)),
                ('add_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=16)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
                ('winter', models.CharField(blank=True, max_length=16)),
                ('summer', models.CharField(blank=True, max_length=16)),
                ('autumn', models.CharField(blank=True, max_length=16)),
                ('spring', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fam', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('otc', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=512)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval_app.pereval')),
            ],
        ),
        migrations.AddField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perevals', to='pereval_app.user'),
        ),
    ]
