# Generated by Django 5.2.7 on 2025-10-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='pereval',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='longitude',
        ),
        migrations.AddField(
            model_name='pereval',
            name='coords',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval_app.coords'),
        ),
        migrations.CreateModel(
            name='PerevalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.image')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval_app.pereval')),
            ],
            options={
                'unique_together': {('pereval', 'image')},
            },
        ),
    ]
